import QRCodeStyling from 'qr-code-styling';

export interface QREngineConfig {
  data: string;
  fgColor: string;
  bgColor: string;
  dotsType: 'square' | 'dots' | 'rounded' | 'classy';
  cornersType: 'square' | 'extra-rounded' | 'dot';
  logo?: string;
  errorLevel?: 'L' | 'M' | 'Q' | 'H';
}

export class QREngine {
  private config: QREngineConfig;
  
  constructor(config: QREngineConfig) {
    this.config = config;
  }

  /**
   * Render QR to canvas at specified resolution
   */
  async renderToCanvas(size: number): Promise<HTMLCanvasElement> {
    const container = document.createElement('div');
    container.style.position = 'absolute';
    container.style.left = '-9999px';
    document.body.appendChild(container);
    
    const qr = new QRCodeStyling({
      width: size,
      height: size,
      data: this.config.data,
      dotsOptions: {
        color: this.config.fgColor,
        type: this.config.dotsType,
      },
      cornersSquareOptions: {
        color: this.config.fgColor,
        type: this.config.cornersType,
      },
      backgroundOptions: {
        color: this.config.bgColor,
      },
      image: this.config.logo || undefined,
      imageOptions: {
        crossOrigin: 'anonymous',
        margin: Math.round(size * 0.035),
      },
      qrOptions: {
        errorCorrectionLevel: this.config.errorLevel || 'H',
      },
    });
    
    qr.append(container);
    await new Promise(resolve => setTimeout(resolve, 300));
    
    const canvas = container.querySelector('canvas');
    document.body.removeChild(container);
    
    if (!canvas) throw new Error('Failed to render QR to canvas');
    return canvas;
  }

  /**
   * Export as high-res PNG blob
   */
  async exportPNG(dpi: number = 300, sizeInches: number = 2): Promise<Blob> {
    const pxSize = Math.round(sizeInches * dpi);
    const canvas = await this.renderToCanvas(pxSize);
    return new Promise((resolve, reject) => {
      canvas.toBlob((blob) => {
        if (blob) resolve(blob);
        else reject(new Error('Failed to create PNG blob'));
      }, 'image/png');
    });
  }

  /**
   * Export as SVG string
   */
  async exportSVG(): Promise<string> {
    const container = document.createElement('div');
    container.style.position = 'absolute';
    container.style.left = '-9999px';
    document.body.appendChild(container);
    
    const qr = new QRCodeStyling({
      width: 600,
      height: 600,
      data: this.config.data,
      dotsOptions: { color: this.config.fgColor, type: this.config.dotsType },
      cornersSquareOptions: { color: this.config.fgColor, type: this.config.cornersType },
      backgroundOptions: { color: this.config.bgColor },
      image: this.config.logo || undefined,
      qrOptions: { errorCorrectionLevel: this.config.errorLevel || 'H' },
    });
    
    qr.append(container);
    await new Promise(resolve => setTimeout(resolve, 300));
    
    const svgEl = container.querySelector('svg');
    document.body.removeChild(container);
    
    if (!svgEl) throw new Error('Failed to generate SVG');
    return new XMLSerializer().serializeToString(svgEl);
  }

  /**
   * Export as PDF (A4, 300dpi)
   */
  async exportPDF(): Promise<Blob> {
    const { jsPDF } = await import('jspdf');
    
    // Generate high-res canvas
    const canvas = await this.renderToCanvas(600); // 300dpi at 2"
    
    // Create PDF
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });
    
    const imgData = canvas.toDataURL('image/png');
    
    // Add title
    pdf.setFontSize(16);
    pdf.text('QR Code — Print Ready', 105, 20, { align: 'center' });
    
    // Add QR code centered on page
    const qrSizeMM = 50; // ~2 inches
    const xPos = (210 - qrSizeMM) / 2; // Center on A4
    pdf.addImage(imgData, 'PNG', xPos, 40, qrSizeMM, qrSizeMM);
    
    // Add print instructions
    pdf.setFontSize(8);
    pdf.text('Generated by EzQR.IO', 105, 100, { align: 'center' });
    pdf.text(`Date: ${new Date().toISOString().split('T')[0]} · Resolution: 300dpi · Size: 2"×2"`, 105, 106, { align: 'center' });
    pdf.text('Minimum print size: 1.2"×1.2" (3×3 cm) · Scan distance: 10-25 cm', 105, 112, { align: 'center' });
    
    // Add crop marks
    this.addCropMarks(pdf, xPos, 40, qrSizeMM);
    
    // Add bleed area guides
    this.addBleedGuides(pdf, xPos, 40, qrSizeMM);
    
    return new Blob([pdf.output('arraybuffer')], { type: 'application/pdf' });
  }
  
  private addCropMarks(pdf: any, x: number, y: number, size: number) {
    pdf.setDrawColor(0);
    pdf.setLineWidth(0.2);
    // Corner marks
    const markLen = 3;
    pdf.line(x - 2, y - 2, x - 2 + markLen, y - 2);
    pdf.line(x - 2, y - 2, x - 2, y - 2 + markLen);
    
    pdf.line(x + size + 2, y - 2, x + size + 2 - markLen, y - 2);
    pdf.line(x + size + 2, y - 2, x + size + 2, y - 2 + markLen);
    
    pdf.line(x - 2, y + size + 2, x - 2 + markLen, y + size + 2);
    pdf.line(x - 2, y + size + 2, x - 2, y + size + 2 - markLen);
    
    pdf.line(x + size + 2, y + size + 2, x + size + 2 - markLen, y + size + 2);
    pdf.line(x + size + 2, y + size + 2, x + size + 2, y + size + 2 - markLen);
  }
  
  private addBleedGuides(pdf: any, x: number, y: number, size: number) {
    pdf.setDrawColor(200);
    pdf.setLineWidth(0.1);
    pdf.setLineDashPattern([2, 2], 0);
    pdf.rect(x - 3, y - 3, size + 6, size + 6);
    pdf.setLineDashPattern([], 0);
  }
}
