/**
 * Convert SVG string to EPS (Encapsulated PostScript)
 * 
 * EPS is the industry standard for professional print.
 * This converts SVG paths to PostScript operators.
 */

export function svgToEps(svgString: string, options?: {
  width?: number;    // points (1/72 inch)
  height?: number;
  title?: string;
  bgColor?: string;
}): string {
  const width = options?.width || 612;  // default: 8.5" at 72pt/in
  const height = options?.height || 612; // default: 8.5"
  const title = options?.title || 'QR Code - EzQR.IO';
  const date = new Date().toISOString();

  return `%!PS-Adobe-3.0 EPSF-3.0
%%BoundingBox: 0 0 ${width} ${height}
%%Title: ${title}
%%Creator: A2ZQR / EzQR.IO
%%CreationDate: ${date}
%%DocumentData: Clean7Bit
%%LanguageLevel: 2
%%EndComments
%%BeginProlog

%!PS
%%EndProlog
%%BeginSetup
%%EndSetup

% -- Begin QR Code Drawing --
% Scale to fill the page with margin
% Assuming QR should be ~2" × 2" centered on page
% At 72pt/inch, 2" = 144pt
% Center: (${width}/2 - 72) to (${width}/2 + 72)

gsave

% Set background color
newpath
0 0 moveto
${width} 0 lineto
${width} ${height} lineto
0 ${height} lineto
closepath
${parseEpsColor(options?.bgColor || '#FFFFFF')} setrgbcolor
fill

% Translate to center
${width / 2 - 72} ${height / 2 - 72} translate
% Scale to fit 144pt box
% (Actual SVG paths translated below)

% -- SVG paths converted to PostScript --
${convertSvgPathsToPostScript(svgString)}

grestore

% -- Cut line guides --
0.2 setlinewidth
[2 2] setdash
0 setgray
% Outer box at 3mm (≈8.5pt) bleed
-8.5 -8.5 moveto
${width + 17} -8.5 lineto
${width + 17} ${height + 17} lineto
-8.5 ${height + 17} lineto
closepath
stroke

% -- Printer notes --
/Times-Roman findfont 6 scalefont setfont
0 setgray
${width} 0 moveto
(Generated by EzQR.IO - Free for commercial use) dup stringwidth pop neg -8 rmoveto show

%%EOF`;
}

/**
 * Parse hex color to RGB for PostScript
 */
function parseEpsColor(hex: string): string {
  const clean = hex.replace('#', '');
  const r = parseInt(clean.slice(0, 2), 16) / 255;
  const g = parseInt(clean.slice(2, 4), 16) / 255;
  const b = parseInt(clean.slice(4, 6), 16) / 255;
  return `${r} ${g} ${b}`;
}

/**
 * Basic SVG path to PostScript conversion
 */
function convertSvgPathsToPostScript(svgString: string): string {
  // Parse SVG XML, extract path elements
  const pathRegex = /<path[^>]*d="([^"]*)"/g;
  let match;
  let ps = '';
  
  while ((match = pathRegex.exec(svgString)) !== null) {
    const d = match[1];
    ps += convertPathDataToPS(d) + '\n';
  }
  
  // Also handle rect elements (QR modules)
  const rectRegex = /<rect[^>]*x="([^"]*)"[^>]*y="([^"]*)"[^>]*width="([^"]*)"[^>]*height="([^"]*)"[^>]*fill="([^"]*)"/g;
  
  while ((match = rectRegex.exec(svgString)) !== null) {
    const [, x, y, w, h, fill] = match;
    const color = parseEpsColor(fill);
    ps += `${color} setrgbcolor
${x} ${y} moveto
${w} 0 rlineto
0 ${h} rlineto
${-w} 0 rlineto
closepath
fill\n`;
  }
  
  return ps;
}

/**
 * Parse SVG path data (simplified - handles M, L, Q, C, Z)
 */
function convertPathDataToPS(d: string): string {
  // Split into commands
  const commands = d.replace(/([MLQCZ])/g, '\n$1 ').trim().split('\n');
  let ps = '';
  
  for (const cmd of commands) {
    if (!cmd.trim()) continue;
    const parts = cmd.trim().split(/\s+/);
    const op = parts[0];
    const args = parts.slice(1).map(Number);
    
    switch (op) {
      case 'M': ps += `${args[0]} ${args[1]} moveto\n`; break;
      case 'L': ps += `${args[0]} ${args[1]} lineto\n`; break;
      case 'C': ps += `${args[0]} ${args[1]} ${args[2]} ${args[3]} ${args[4]} ${args[5]} curveto\n`; break;
      case 'Q': ps += `${args[0]} ${args[1]} ${args[2]} ${args[3]} rcurveto\n`; break;
      case 'Z': ps += 'closepath\n'; break;
    }
  }
  
  return ps + 'fill\n';
}

/**
 * Main EPS export function
 */
export async function exportEPS(svgString: string, title?: string, bgColor?: string): Promise<Blob> {
  const epsContent = svgToEps(svgString, { title, bgColor });
  return new Blob([epsContent], { type: 'application/postscript' });
}
